(function(){'use strict';
const key='resale-ledger-v1',L=window.LedgerLogic;let db;try{db=JSON.parse(localStorage.getItem(key))||{products:[],transactions:[]}}catch{db={products:[],transactions:[]}};let page='overview',formType='';
const $=s=>document.querySelector(s),money=n=>(n/100).toLocaleString('en-US',{style:'currency',currency:'USD'}),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),id=()=>globalThis.crypto?.randomUUID?.()||('id-'+Date.now()+'-'+Math.random().toString(36).slice(2)),today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(key,JSON.stringify(db));render()}function notify(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}function calc(){return L.calculate(db)}
const products=()=>Object.fromEntries(db.products.map(p=>[p.id,p]));
const pname=id=>products()[id]?.name||'未知商品';
function heading(title,description,buttons=''){return '<div class="section-title"><div><h1>'+title+'</h1><p>'+description+'</p></div><div class="actions">'+buttons+'</div></div>'}
function button(label,action){return '<button class="btn btn-main" data-action="'+action+'">'+label+'</button>'}
function grid(rows){return '<div class="panel"><table><thead><tr>'+rows[0].map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(1).map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function render(){let m;try{m=calc()}catch(e){$('#view').innerHTML='<div class="panel danger">'+escape(e.message)+'</div>';return}
document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));
const labels={overview:'总览',products:'商品库存',ledger:'交易流水',analytics:'利润分析'};$('#crumb').textContent=labels[page];
if(page==='overview'){const boxes=[['累计销售额',money(m.revenue)],['已实现利润',money(m.profit)],['剩余库存件数',m.quantity],['库存采购成本',money(m.inventory)]];
$('#view').innerHTML=heading('经营总览','你的库存与盈利一目了然',button('＋ 采购入库','add-purchase')+' '+button('添加商品','add-product'))+'<div class="cards">'+boxes.map(([a,b])=>'<div class="metric"><small>'+a+'</small><strong>'+b+'</strong></div>').join('')+'</div><div class="panel"><h2>最近销售</h2>'+salesTable(m.sales.slice(-8).reverse())+'</div><div class="actions">'+button('载入演示数据','demo')+'<button class="btn btn-soft" data-action="export-json">导出 JSON 备份</button></div>';}
if(page==='products'){$('#view').innerHTML=heading('商品库存','按 SKU 查看现有库存',button('添加商品','add-product')+' '+button('采购入库','add-purchase'))+grid([['商品 / SKU','分类','现有库存','剩余成本','状态','操作'],...db.products.map(p=>[escape(p.name)+'<div class="muted">'+escape(p.sku)+'</div>',escape(p.category||'其他'),m.stats[p.id].quantity,money(m.stats[p.id].value),m.stats[p.id].quantity<=Number(p.threshold||0)?'<span class="danger">低库存</span>':'<span class="pill">正常</span>','<button class="btn btn-soft" data-delete-product="'+escape(p.id)+'">删除</button>'])]);}
if(page==='ledger'){$('#view').innerHTML=heading('交易流水','每笔进货与销售记录',button('＋ 进货','add-purchase')+' '+button('＋ 销售','add-sale'))+grid([['日期','类型','商品','数量','金额','操作'],...db.transactions.slice().reverse().map(t=>[escape(t.date),t.type==='purchase'?'入库':'销售',escape(pname(t.productId)),t.quantity,money(L.money(t.type==='purchase'?t.unitCost:t.unitPrice)*t.quantity),'<button class="btn btn-soft" data-delete-tx="'+escape(t.id)+'">删除</button>'])])+'<div class="actions"><button class="btn btn-soft" data-action="export-csv">导出 CSV</button><button class="btn btn-soft" data-action="import-json">导入 JSON</button></div>';}
if(page==='analytics'){$('#view').innerHTML=heading('利润分析','基于 FIFO 进货成本、手续费和发货运费')+'<div class="cards">'+[['销售收入',money(m.revenue)],['进货成本',money(m.cost)],['交易费用',money(m.fees+m.shipping)],['已实现利润',money(m.profit)]].map(([a,b])=>'<div class="metric"><small>'+a+'</small><strong>'+b+'</strong></div>').join('')+'</div>'+grid([['商品','售出件数','销售额','利润'],...db.products.map(p=>[escape(p.name),m.stats[p.id].sold,money(m.stats[p.id].revenue),money(m.stats[p.id].profit)])]);}
}
function salesTable(sales){if(!sales.length)return'<div class="empty">暂无销售记录。添加商品并入库后，就能记录销售。</div>';return'<table><tr><th>日期</th><th>商品</th><th>收入</th><th>成本</th><th>利润</th></tr>'+sales.map(s=>'<tr><td>'+escape(s.date)+'</td><td>'+escape(pname(s.productId))+'</td><td>'+money(s.revenue)+'</td><td>'+money(s.cost)+'</td><td>'+money(s.profit)+'</td></tr>').join('')+'</table>'}
function field(name,label,type='text',extra='',wide=false){return'<label class="field '+(wide?'wide':'')+'">'+label+'<input name="'+name+'" type="'+type+'" '+extra+' required /></label>'}
function selectProduct(){return'<label class="field wide">商品<select name="productId" required>'+db.products.map(p=>'<option value="'+escape(p.id)+'">'+escape(p.name)+' ('+escape(p.sku)+')</option>').join('')+'</select></label>'}
function open(type){formType=type;if(type!=='product'&&!db.products.length){notify('请先添加商品');return}$('#formError').hidden=true;
const labels={product:'添加商品',purchase:'采购入库',sale:'记录销售'};$('#dialogTitle').textContent=labels[type];$('#submitText').textContent='保存记录';let f='';
if(type==='product')f=field('name','商品名称','text','maxlength="120"',true)+field('sku','SKU / 商品编码','text','maxlength="80"')+field('category','分类','text','value="其他"')+field('threshold','低库存预警件数','number','min="0" step="1" value="2"');
if(type==='purchase')f=selectProduct()+field('quantity','入库件数','number','min="1" step="1" value="1"')+field('unitCost','单件进货成本 ($)','number','min="0" step=".01" value="0"')+field('freight','此批次总运费 ($)','number','min="0" step=".01" value="0"')+field('date','日期','date','value="'+today()+'"');
if(type==='sale')f=selectProduct()+field('quantity','销售件数','number','min="1" step="1" value="1"')+field('unitPrice','单件成交价 ($)','number','min="0" step=".01" value="0"')+field('fee','整单手续费 ($)','number','min="0" step=".01" value="0"')+field('shipping','整单发货运费 ($)','number','min="0" step=".01" value="0"')+field('channel','销售渠道','text','value="线下"')+field('date','日期','date','value="'+today()+'"');
$('#formFields').innerHTML='<div class="form-grid">'+f+'</div>';$('#entryDialog').showModal()}
$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{let item;if(formType==='product'){if(!o.name.trim()||!o.sku.trim())throw Error('填写名称和 SKU');if(db.products.some(p=>p.sku.toLowerCase()===o.sku.trim().toLowerCase()))throw Error('SKU 已存在');item={id:id(),name:o.name.trim(),sku:o.sku.trim(),category:o.category.trim(),threshold:Math.max(0,Number(o.threshold)||0)};db.products.push(item)}
else{const quantity=L.integer(o.quantity);if(formType==='purchase'){L.money(o.unitCost);L.money(o.freight)}else{L.money(o.unitPrice);L.money(o.fee);L.money(o.shipping);if(calc().stats[o.productId].quantity<quantity)throw Error('库存不足，不能出售')}item={...o,id:id(),type:formType,quantity};db.transactions.push(item);calc()}
save();$('#entryDialog').close();notify('保存成功')}catch(err){if(formType!=='product'&&db.transactions.at(-1)?.id===item?.id)db.transactions.pop();$('#formError').textContent=err.message;$('#formError').hidden=false}});
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(){const rows=[['date','type','sku','product','quantity','unit_cost','unit_price','freight','fee','shipping','channel'],...db.transactions.map(t=>[t.date,t.type,products()[t.productId]?.sku||'',pname(t.productId),t.quantity,t.unitCost||'',t.unitPrice||'',t.freight||'',t.fee||'',t.shipping||'',t.channel||''])];download('transactions.csv','\uFEFF'+rows.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){page=nav.dataset.nav;render();return}const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='add-product')open('product');if(act==='add-purchase')open('purchase');if(act==='add-sale')open('sale');if(act==='close-dialog')$('#entryDialog').close();if(act==='export-json')download('resale-ledger-backup.json',JSON.stringify(db,null,2),'application/json');if(act==='export-csv')csv();if(act==='import-json')$('#importInput').click();if(act==='demo'){if(db.products.length||db.transactions.length){notify('演示数据只能在空账本加载');return}db.products=[{id:'p1',name:'示例：球鞋',sku:'DEMO-001',category:'球鞋',threshold:2}];db.transactions=[{id:'t1',type:'purchase',productId:'p1',quantity:3,unitCost:'100',freight:'6',date:today()},{id:'t2',type:'sale',productId:'p1',quantity:1,unitPrice:'160',fee:'6',shipping:'9',date:today(),channel:'线下'}];save();notify('已载入演示数据')}}const tx=e.target.closest('[data-delete-tx]');if(tx&&confirm('确定删除这笔交易吗？')){const next=db.transactions.filter(t=>t.id!==tx.dataset.deleteTx);try{L.calculate({...db,transactions:next});db.transactions=next;save()}catch(err){notify('无法删除：'+err.message)}}const p=e.target.closest('[data-delete-product]');if(p&&confirm('确定删除该商品吗？')){if(db.transactions.some(t=>t.productId===p.dataset.deleteProduct)){notify('该商品有交易记录，不可删除');return}db.products=db.products.filter(x=>x.id!==p.dataset.deleteProduct);save()}});
$('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const next=JSON.parse(await file.text());if(!Array.isArray(next.products)||!Array.isArray(next.transactions))throw Error('无效备份格式');L.calculate(next);if(confirm('导入会覆盖本机现有账本。继续吗？')){db=next;save();notify('导入成功')}}catch(err){notify('导入失败：'+err.message)}e.target.value=''});render();
})();